version: "2"
services:
#  aircasting:
#    build:
#      context: .
#    ports:
#      - 3000:3000
#    environment:
#      RAILS_SERVE_STATIC_FILES: 'true'
#      RAILS_LOG_TO_STDOUT: 'true'
#      RAILS_ENV: 'production'
#      GOOGLE_MAPS_API_KEY: AIzaSyDaP4UR4matiWd9J2dg3sv6SJepSMJycn8
#      MYSQL_DATABASE: aircasting_production
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root-password
#      MYSQL_HOST: aircasting-db
  aircasting-db:
    image: mariadb:10.5.4
    restart: unless-stopped
    ports:
      - 3001:3306
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: aircasting_production
      MYSQL_USER: aircasting-user
      MYSQL_PASSWORD: aircasting-user-password
  aircasting-redis:
    image: redis:6.0.9
    ports:
      - 3002:6379
    labels:
      project: de4l
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
